### ISSUE TITLE
[ADD] Music Presence

### ISSUE THREAD

**Issue by ungive** [NoPlagiarism/awesome-discord-activities#4]
# Add Request
**Link to repo**

https://github.com/ungive/discord-music-presence

Preferred link: https://musicpresence.app

The domain currently points to the GitHub repository, but will soon link to a real website for the project. You can verify that the domain is really owned by me (the maintainer of the project) by checking the "Verified" badge in the [music-presence](https://github.com/music-presence) GitHub organization that is owned by me (this badge only shows if the domain that is visible there is verified via DNS records).

**Short Description**

*Share music from any media player in your Discord status: The missing counterpart to Spotify's exclusive "Listening to" status*

**Detailed Description**

Music Presence allows you to share what music you are listening to in your Discord status. It has the following features:

- Works with any media player/application on your system
- Shows a cover image in your status 100% of the time, without the need for external image sources
- Obsoletes any plugins for specific media players: it's a single solution for all media players with unified controls and customization
- Fine-grained control over which applications are shared and what your status looks like
- The tray icon changes and reflects whether your status is currently active or not
- Available for Windows and Mac

I've put a lot of work into this application over the last months and I'd love for it to be featured on your list!

If you have any questions I am happy to answer them.

---

![banner](https://github.com/user-attachments/assets/e1102e53-9f9d-43d7-8271-f330d667493a)

**Comment by NoPlagiarism** [comment]
Good Work! Added to list
